AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  MySNSTopic:
    Type: AWS::SNS::Topic
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.9
      PackageType: Zip
      InlineCode: |
        # Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
        # SPDX-License-Identifier: Apache-2.0
        def lambda_handler(event, context):
            for record in event['Records']:
                process_message(record)
            print("done")

        def process_message(record):
            try:
                message = record['Sns']['Message']
                print(f"Processed message {message}")
                # TODO; Process your record here

            except Exception as e:
                print("An error occurred")
                raise e
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MySNSTopic
Outputs:
  TopicArn:
    Description: The ARN of the created SNS topic
    Value: !Ref MySNSTopic
  TopicName:
    Description: The name of the created SNS topic
    Value: "SampleTopic"
         
